[package]
name = "read_smbios"
version = "0.1.0"
authors = ["keith"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["sysinfoapi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
